ROOT='C:\\Pycharm\\Projects\\polydiavlika\\polydiavlika\\'
TRAFFIC_DATASETS_FOLDER='traffic_datasets\\'
#PROPAGATION_TIME=12/(3e8)
PROPAGATION_TIME=0
TOLERANCE = 1e-9
N_collision = 16
T_send = 1e-4
T_load = 4e-5
T_idle = (2.56e-8)+2*PROPAGATION_TIME
timestep = 0.8e-9